### ISSUE TITLE
Cielo OAUTH - Erro 404

### ISSUE THREAD

**Issue by marcobraghim** [DeveloperCielo/developercielo.github.io#173]
Não sei onde seria o melhor lugar para abrir essa questão, portanto peço ajuda com isso também.

Estou tentando realizar a autenticação conforme documentação no link abaixo, mas estou recebendo a seguinte mensagem de erro:

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

https://docscielo.github.io/Pilots/manual/controletransacional4#request

---

Segue código php que estou utilizando

```php
        $clientConcat = "$clientId:$clientSecret";

        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, "https://cieloecommerce.cielo.com.br/v2/public/v2/token");
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_POST, true);
        curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode(array('grant_type' => 'client_credentials')));
        curl_setopt($curl, CURLOPT_HTTPHEADER, array(
            'Authorization: Basic '. base64_encode($clientConcat),
            'Content-Type: application/x-www-form-urlencoded'
        ));

        $response = curl_exec($curl);
        curl_close($curl);
        $json = json_decode($response);

        exit($response);
```

**Comment by marcobraghim** [comment]
Tentei atualizar para a seguinte linha e continua não funcionando:

```php
curl_setopt($curl, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
```

**Comment by dhieyson** [comment]
Utilize o endpoint `https://cieloecommerce.cielo.com.br/api/public/v2/token` para obter o token

**Comment by marcobraghim** [comment]
Funcionou! Peço por gentileza que atualize o endpoint na documentação para que outras pessoas não tenham o mesmo problema.

Muito obrigado!

**Comment by dhieyson** [comment]
A documentação será atualizada. Obrigado pelo feedback

**Comment by procarrera** [comment]
Alguem pode me ajudar a testar o OAUTH pelo Insomnia?

**Comment by marcobraghim** [comment]
> Alguem pode me ajudar a testar o OAUTH pelo Insomnia?
> eu nao entendi aonde devo inserir minhas credencias concatenadas...

Nos headers...

**Comment by procarrera** [comment]
> > Alguem pode me ajudar a testar o OAUTH pelo Insomnia?
> > eu nao entendi aonde devo inserir minhas credencias concatenadas...
> 
> Nos headers...

Sim, consegui depois!
eu estava colocando as credencias dentro de { }, no entanto deveria estar sem colchetes.
