### ISSUE TITLE
Erro 500 com solicitação para /1/card (tokenizar cartão)

### ISSUE THREAD

**Issue by rodriigovieira** [DeveloperCielo/developercielo.github.io#272]
Estou recebendo um erro 500 ao tentar tokenizar um cartão no endpoint `/1/card`. Estou usando o ambiente sandbox.

Essa é a cópia do comando cUURL que estou usando:

```
curl
--request POST "https://apisandbox.cieloecommerce.cielo.com.br/1/card/"
--header "Content-Type: application/json"
--data-binary
{
    "CustomerName": "Comprador Teste Cielo",
    "CardNumber":"4532117080573700",
    "Holder":"Comprador T Cielo",
    "ExpirationDate":"12/2025",
    "Brand":"Visa"
}
--verbose
```

**Comment by dhieyson** [comment]
Para tokenizar um cartão, o mesmo dever ser válido. Utilize um site de gerador de números válidos de cartão (ou implemente um gerador respeitando o "mod 10") 

Mesmo sendo ambiente sandbox não é recomendado você expor suas credenciais (MerchantId / MerchantKey)

**Comment by ahmadabdouni** [comment]
Como falado acima pelo @dhieyson, Deve ser utilizado um cartão valido para tokenizar, por esse motivo esta ocorrendo a negativa do erro 500.

Att

**Comment by rodriigovieira** [comment]
Muito obrigado! @ahmadabdouni @dhieyson 
Testei aqui e funcionou perfeitamente. Seria legal uma mensagem de erro explicando o problema. 

Valeu!
