### ISSUE TITLE
Códigos de retorno ABECS

### ISSUE THREAD

**Issue by alissonperez** [DeveloperCielo/developercielo.github.io#341]
Olá, estou implementando uma integração que vai usar os códigos de retorno da Abecs, não estou conseguindo simular como eles retornam na API. A documentação não deixa muito claro em qual campo consigo esses valores de retorno (nem como poderia ativa-los).

**Comment by gajooliveira14** [comment]
show, vou ver com o pessoal!

**Comment by gajooliveira14** [comment]
já mandei um whatsapp para o Joni lá da parte técnica da Rede. Vamos ver o que ele responde.
