### ISSUE TITLE
Autenticação 3DS sem SDK

### ISSUE THREAD

**Issue by lvilasboas** [DeveloperCielo/developercielo.github.io#345]
Boa tarde,

gostaria de saber se é possível realizar a autenticação 3DS **sem** utilizar os SDKs disponíveis na documentação.

Assim conforme mencionado no #333 (que foi aberto há praticamente um ano e meio atrás, sem qualquer tipo de resposta), esse problema já era muito real na época, e só é mais real ainda hoje em dia.

E outra dúvida também, como realizar o preenchimento dos campos dos dados dos cartões se o cliente utilizar um cartão previamente tokenizado?

**Comment by ellencsilva** [comment]
Olá,

Segue resposta da área técnica:

1 - Não damos suporte para autenticação 3DS fora do que está documentação.

2 - O autenticador ainda não suporta a abertura de cartões tokenizados.
