### ISSUE TITLE
Expor MerchantId e MerchantKey em chamadas Javascript.

### ISSUE THREAD

**Issue by volnei** [DeveloperCielo/developercielo.github.io#346]
Existe algum risco na exposição dessas informações para chamadas via Javscript? A ideia é não ter que passar as informações para o backend, mas para isso essas informações ficariam expostas no front end.

Obrigado

**Comment by ellencsilva** [comment]
Olá,
Para obter suporte da Cielo, por favor entre em contato com cieloecommerce@cielo.com.br.
