### ISSUE TITLE
Questions about the expiration of a capture after pre-authorization

### ISSUE THREAD

**Issue by SirAppSec** [DeveloperCielo/developercielo.github.io#354]
We are trying to make adjustments to one of our products to accommodate the use of the api in our billing flow.
We need to make a transaction after authenticating during the span of a maximum of a month.
when the shipment of the product has been delivered we would want to bill the card from a stored Token.

I've checked the documentation at [https://developercielo.github.io/en/manual/cielo-ecommerce#payment-methods](https://developercielo.github.io/en/manual/cielo-ecommerce#payment-methods)
which states that 
```"When making a pre-authorization, it is necessary to confirm it, so that the charge is effected to the card carrier. It is through this operation a pre-authorization is effected, and it can be executed normally within 5 days after the pre-authorization date."```

1. Can we increase the time of execution for up to 30 days? 

Another option is making a recurring payment, which stores the amount, buyer info. And canceling after the first payment.
2. It seems like a work around, but can it be done "behind the scene"? without the user being notified of a recurring payment?

Another question regarding the compliance of the tokenization, we want to understand whether we must store the card token in an encrypted channel.
3. So, in the event a third party has identified a card token, can it be used to make payments using another Cielo merchant account? or is the token unique to our merchant making the original request?

**Comment by ellencsilva** [comment]
Hello,

**Comment by ellencsilva** [comment]
Hello,
Please send an e-mail to cieloecommerce@cielo.com.br to contact Cielo Support.

**Comment by souzadavi** [comment]
Hi @SirAppSec 

1. direct to cielo
2. direct to cielo
3. The token is unique to your merchant id and key. Cielo said it.
