### ISSUE TITLE
Site do webservice 3.0 fora do ar?

### ISSUE THREAD

**Issue by jsabino** [DeveloperCielo/developercielo.github.io#36]
Não estou conseguindo mais acessar o site da documentação da API do e-Commerce Cielo.

https://developercielo.github.io/manual/cielo-ecommerce
ou
http://developercielo.github.io/Webservice-3.0/

Foi movido?

**Comment by netojoaobatista** [comment]
[O link do manual é o primeiro que você postou](https://developercielo.github.io/manual/cielo-ecommerce).
