### ISSUE TITLE
The requested URL returned error: 500 Internal Server Error

### ISSUE THREAD

**Issue by albertguedes** [DeveloperCielo/developercielo.github.io#41]
Esse erro vem ocorrendo no endereço da api sandbox :

apisandbox.cieloecommerce.cielo.com.br (104.41.42.101) port 443

**Comment by netojoaobatista** [comment]
Qual o contexto? Qual requisição está enviando exatamente, que está causando esse tipo de erro. Ainda, o erro começou quando?

**Comment by albertguedes** [comment]
Requisição de compra simples com cartão de crédito.
A requisição estava dando retorno normalmente, não mudei nenhuma configuração, e começou a dar erro 500 nas últimas transações de teste. Única modificação que eu fiz foi o valor do merchant order id.

**Comment by netojoaobatista** [comment]
Isso pode ser temporário; talvez esteja havendo algum deploy que esteja causando esse tipo de retorno.

Você pode aguardar alguns instantes e tentar novamente, ou enviar o json e a URL de requisição para vermos se tem algum problema nele.

**Comment by albertguedes** [comment]
Estou usando o curl do Postman:

`<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://apisandbox.cieloecommerce.cielo.com.br/1/sales",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "{\r\n   \"MerchantOrderId\":\"2014111703\",\r\n   \"Payment\":{\r\n     \"Provider\":\"Simulado\",\r\n     \"Type\":\"CreditCard\",\r\n     \"Amount\":15700,\r\n     \"Installments\":1,\r\n     \"SoftDescriptor\":\"123456789ABCD\",\r\n     \"CreditCard\":{\r\n         \"CardNumber\":\"4551870000000184\",\r\n         \"Holder\":\"Teste Holder\",\r\n         \"ExpirationDate\":\"12/2021\",\r\n         \"SecurityCode\":\"123\",\r\n         \"Brand\":\"ELO\"\r\n     }\r\n   }\r\n}",
  CURLOPT_HTTPHEADER => array(
    "Cache-Control: no-cache",
    "Content-Type: application/json",
    "MerchantId: ****",
    "MerchantKey: *****",
    "Postman-Token: *****"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}`

**Comment by frekele** [comment]
Estou tendo o mesmo problema desde sábado a tarde.

Criando uma transação simples no Postman, como a do exemplo do manual:

### Exemplo:
![ecommerce-print0](https://user-images.githubusercontent.com/2288215/35231189-4a826402-ff7f-11e7-8c51-ac9d505bf005.png)

### Header
![ecommerce-print1](https://user-images.githubusercontent.com/2288215/35231197-4fd2e526-ff7f-11e7-87e8-18d95beee104.png)

### Body
![ecommerce-print2](https://user-images.githubusercontent.com/2288215/35231211-5559b074-ff7f-11e7-953f-0b82ba926a6a.png)

### Obtemos o request:
500 - Internal Server Error

**Comment by netojoaobatista** [comment]
O problema ainda persiste? Aqui está funcionando em Sandbox exatamente como esperado.

**Comment by frekele** [comment]
@netojoaobatista 

Voltou a funcionar ontem a tarde.

Obrigado pelo feedback.
