### ISSUE TITLE
Problema no resgate do Access-Token no portal de desenvolvedor

### ISSUE THREAD

**Issue by lmarquesmoreira** [DeveloperCielo/developercielo.github.io#52]
Bom dia, 

Estou com o seguinte problema: ao criar uma nova credencial para um App não está sendo gerado um Access-Token. 
Para integração local é necessário esse Access-Token, o que posso fazer?

https://desenvolvedores.cielo.com.br/api-portal/pt-br/myapps

![noaccesstokencielodev](https://user-images.githubusercontent.com/3696197/41401066-3a82118e-6f95-11e8-8edb-f4466953abf3.png)

**Comment by frekele** [comment]
Olá @lmarquesmoreira ,

Eu não trabalho na Cielo, mas já te digo que o suporte ao desenvolvedor deles é muito à desejar, principalmente se for por aqui no Github, tenho tickets e issues que foram respondidas superficialmente e nunca fora resolvidas, e posteriormente sem mais sem menos foram fechadas, fiquei no vácuo.

Sem falar que os componentes API Client para, php, java , dotNet e outros é muito ruim, são gerados através do gerador swagger, ou seja caso você queira fazer uma PR se torna totalmente inviável colaborar. Eu particularmente precisei criar um componente próprio para consumir a API.

Para obter um feedback melhor da Cielo, você deve abrir um ticket aqui: https://devcielo.zendesk.com

Abraços

**Comment by lmarquesmoreira** [comment]
@frekele Obrigado pelas dicas o/
